services:
  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j-chorus
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./data/neo4j:/data
      - ./data/neo4j-logs:/logs

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-chorus
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage:z
      - ./qdrant.config.yaml:/qdrant/config/production.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - QDRANT__GPU__INDEXING=true  # Enable GPU indexing in config
